module cartesianLattice_class

  use numPrecision
  use universalVariables, only : INF, SURF_TOL
  use genericProcedures,  only : fatalError, numToChar
  use dictionary_class,   only : dictionary

  implicit none
  private

  ! Parameters
  ! Note X/Y/Z MIN/MAX MUST have the value they have (or generated by a function)
  ! Public so they can be accessed by unit tests
  integer(shortInt), public, parameter :: X_MIN = -1, X_MAX = -2, Y_MIN = -3, Y_MAX = -4, &
                                          Z_MIN = -5, Z_MAX = -6
  
  !!
  !! 2D or 3D Cartesian lattice with constant pitch.
  !! Used in several places across the code, e.g., universe, field, acceleration structure.
  !! Locates the local cell given a point and direction. Returns distance to the next boundary
  !! between local cells.
  !!
  !! Desxcribes a lattice of fixed, finite size (e.g 17x17x2). Centre of the
  !! lattice is placed at the origin. An additional cell is placed beyond the lattice
  !! called background (or out) cell.
  !!
  !! Local ID is 1 in bottom X, Y & Z corner. It increases first with X then Y and lastly Z.
  !!
  !! Minimum lattice pitch is set to 10 * SURF_TOL
  !!
  !! Sample Input Dictionary (3D):
  !!   latt { #origin (0.0 0.0 0.0); #
  !!          shape (3 2 2);
  !!          pitch (1.0 1.0 1.0);
  !!   }
  !!
  !! Sample Input Dictionary (2D):
  !!   latt2D { shape (2 2 0);       // 0 indicates infinite extent in z-axis
  !!            pitch (1.0 1.0 0.0); // Any pitch is allowed in z, use 0.0 for clarity
  !!   }
  !!
  !! Private Members:
  !!  pitch      -> Values of lattice pitch in x, y & z directions
  !!  sizeN      -> Number of lattice cells in x, y & z directions
  !!  corner     -> Location of the minimum corner
  !!  a_bar      -> Halfwidth of lattice cell reduced by surface tolerance
  !!  outLocalID -> LocalID of the background cell
  !!
  type, public :: cartesianLattice
    private
    real(defReal), dimension(3)     :: pitch = ZERO
    integer(shortInt), dimension(3) :: sizeN = 0
    real(defReal), dimension(3)     :: corner = ZERO
    real(defReal), dimension(3)     :: a_bar  = ZERO
    integer(shortInt)               :: outLocalID = 0
  contains
    procedure :: init
    procedure :: kill
    procedure :: findIJK
    procedure :: findCell
    procedure :: distance
    procedure :: getOffset
    procedure :: getNormal
    procedure :: getSize
    procedure :: getCorner
    procedure :: getOrigin
    procedure :: getOutID
  end type cartesianLattice

contains

  !!
  !! Initialise lattice
  !!
  !! Errors:
  !!   fatalError if input is invalid.
  !!
  subroutine init(self, dict)
    class(cartesianLattice), intent(inout)         :: self
    class(dictionary), intent(in)                  :: dict
    real(defReal), dimension(:), allocatable       :: temp
    integer(shortInt), dimension(:), allocatable   :: tempI
    integer(shortInt)                              :: N
    real(defReal), dimension(3)                    :: origin
    character(100), parameter :: Here = 'init (cartesianLattice_class.f90)'

    ! Load pitch
    call dict % get(temp, 'pitch')
    N = size(temp)

    if (N /= 3) then
      call fatalError(Here, 'Pitch must have size 3. Has: '//numToChar(N))
    end if
    self % pitch = temp

    ! Load origin
    if (dict % isPresent('origin')) then
      call dict % get(temp, 'origin')
    else
      temp = ZERO
    end if
    N = size(temp)
    if (N /= 3) then
      call fatalError(Here, 'Origin must have size 3. Has: '//numToChar(N))
    end if
    origin = temp

    ! Load Size
    call dict % get(tempI, 'shape')
    N = size(tempI)

    if (N /= 3) then
      call fatalError(Here, 'Shape must have size 3. Has: '//numToChar(N))
    else if (any(tempI < 0)) then
      call fatalError(Here, 'Shape contains -ve entries')
    end if
    self % sizeN = tempI

    ! Detect reduced Z dimension
    if (self % sizeN(3) == 0) then
      self % sizeN(3) = 1
      self % pitch(3) = TWO * INF
    end if

    ! Check X & Y for 0 size
    if (any( self % sizeN == 0)) call fatalError(Here, 'Shape in X and Y axis cannot be 0.')

    ! Check for invalid pitch
    if (any(self % pitch < 10 * SURF_TOL)) then
      call fatalError(Here, 'Pitch size must be larger than: '//numToChar( 10 * SURF_TOL))
    end if

    ! Calculate halfwidth and corner
    self % a_bar = self % pitch * HALF - self % pitch * SURF_TOL
    self % corner = origin - (self % sizeN * HALF * self % pitch)

    ! Calculate local ID of the background
    self % outLocalID = product(self % sizeN) + 1

  end subroutine init

  !!
  !! Return size of the lattice in each direction
  !!
  pure function getSize(self) result(sizeN)
    class(cartesianLattice), intent(in) :: self
    integer(shortInt), dimension(3)     :: sizeN

    sizeN = self % sizeN

  end function getSize

  !!
  !! Return the corner of the lattice
  !!
  pure function getCorner(self) result(corner)
    class(cartesianLattice), intent(in) :: self
    real(defReal), dimension(3)         :: corner

    corner = self % corner

  end function getCorner

  !!
  !! Return the origin of the lattice
  !!
  pure function getOrigin(self) result(origin)
    class(cartesianLattice), intent(in) :: self
    real(defReal), dimension(3)         :: origin

    origin = self % corner + self % sizeN * HALF * self % pitch

  end function getOrigin

  !!
  !! Return the local ID of the background cell
  !!
  pure function getOutID(self) result(outID)
    class(cartesianLattice), intent(in) :: self
    integer(shortInt)                   :: outID

    outID = self % outLocalID

  end function getOutID

  !!
  !! Find the ijk indices of a given a position
  !!
  pure function findIJK(self, r) result(ijk)
    class(cartesianLattice), intent(in)     :: self
    real(defReal), dimension(3), intent(in) :: r
    integer(shortInt), dimension(3)         :: ijk

    ! Find lattice location in x, y & z
    ijk = floor((r - self % corner) / self % pitch) + 1

  end function findIJK

  !!
  !! Find local cell ID given a point
  !!
  pure function findCell(self, r, u) result(localID)
    class(cartesianLattice), intent(in)     :: self
    real(defReal), dimension(3), intent(in) :: r
    real(defReal), dimension(3), intent(in) :: u
    integer(shortInt)                       :: localID
    integer(shortInt), dimension(3)         :: ijk
    integer(shortInt)                       :: i, inc
    real(defReal), dimension(3)             :: r_bar

    ! Find lattice location in x, y & z
    ijk = self % findIJK(r)

    ! Get position wrt middle of the lattice cell
    r_bar = r - self % corner - ijk * self % pitch + HALF * self % pitch

    ! Check if position is within surface tolerance
    ! If it is, push it to next cell
    do i = 1, 3
      if (abs(r_bar(i)) > self % a_bar(i) .and. r_bar(i)*u(i) > ZERO) then

        ! Select increment. Ternary expression
        if (u(i) < ZERO) then
          inc = -1
        else
          inc = 1
        end if

        ijk(i) = ijk(i) + inc
      end if
    end do

    ! Set localID
    if (any(ijk <= 0 .or. ijk > self % sizeN)) then ! Point is outside lattice
      localID = self % outLocalID

    else
      localID = ijk(1) + self % sizeN(1) * (ijk(2)-1 + self % sizeN(2) * (ijk(3)-1))

    end if

  end function findCell

  !!
  !! Return distance to the next boundary between local cells in the universe
  !!
  !! See universe_inter for details.
  !!
  subroutine distance(self, d, surfIdx, localID, r, u)
    class(cartesianLattice), intent(in)     :: self
    real(defReal), intent(out)              :: d
    integer(shortInt), intent(out)          :: surfIdx
    integer(shortInt), intent(in)           :: localID
    real(defReal), dimension(3), intent(in) :: r
    real(defReal), dimension(3), intent(in) :: u
    real(defReal), dimension(3)             :: r_bar, bounds
    real(defReal)                           :: test_d
    integer(shortInt)                       :: i, ax
    character(100), parameter :: Here = 'distance (cartesianLattice_class.f90)'

    ! Catch case if not inside the lattice
    if (localID == self % outLocalID) then
      call fatalError(Here, 'Cannot calculate distance for background cell')

    end if

    ! Find position wrt lattice cell centre
    ! Need to use localID to properly handle under and overshoots
    r_bar = r - self % corner
    r_bar = r_bar - (get_ijk(localID, self % sizeN) - HALF) * self % pitch

    ! Select surfaces in the direction of the particle
    bounds = sign(self % pitch * HALF, u)

    ! Find minimum distance
    ! Rely on IEEE 754 standard (for floating point numbers)
    ! 0.0/0.0 = NaN and (NaN < A = false; for every A)
    ! A/0.0 = Infinity (if A > 0.0)
    !
    ! Provide default axis to ensure no out of bounds array access if
    ! all distances happen to be infinite
    d = INF
    ax = 1
    do i = 1, 3
      ! Nominator and denominator will have the same sign (by earlier bounds selection)
      test_d = (bounds(i) - r_bar(i)) / u(i)

      if (test_d < d) then
        d = test_d
        ax = i
      end if
    end do

    ! Cap distance value
    d = max(ZERO, d)
    d = min(INF, d)

    ! Generate surface memento
    surfIdx = ax * 2
    if (u(ax) < ZERO) surfIdx = surfIdx - 1
    surfIdx = -surfIdx

  end subroutine distance

  !!
  !! Return the spatial offset of the lattice cell given a localID
  !!
  pure function getOffset(self, localID) result(offset)
    class(cartesianLattice), intent(in)     :: self
    integer(shortInt), intent(in)           :: localID
    real(defReal), dimension(3)             :: offset

    ! Catch case if not inside the lattice
    if (localID == self % outLocalID) then
      offset = ZERO
    else
      offset = (get_ijk(localID, self % sizeN) - HALF) * self % pitch + self % corner
    end if

  end function getOffset
  
  !!
  !! Return normal for the given surfIdx
  !!
  function getNormal(self, surfIdx) result (normal)
    class(cartesianLattice), intent(in) :: self
    integer(shortInt), intent(in)       :: surfIdx
    real(defReal), dimension(3)         :: normal
    character(100), parameter           :: Here = 'getNormal (cartesianLattice_class.f90)'

    ! Convert surfIdx to appropriate axis
    select case(surfIdx)
      case(X_MIN)
        normal = [-1, 0, 0]

      case(X_MAX)
        normal = [1, 0, 0]

      case(Y_MIN)
        normal = [0, -1, 0]
      
      case(Y_MAX)
        normal = [0, 1, 0]

      case(Z_MIN)
        normal = [0, 0, -1]

      case(Z_MAX)
        normal = [0, 0, 1]

      case default
        call fatalError(Here, 'Unrecognised surfIdx: '//numToChar(surfIdx))

    end select

  end function getNormal

  !!
  !! Return to uninitialised state
  !!
  elemental subroutine kill(self)
    class(cartesianLattice), intent(inout) :: self

    self % pitch = ZERO
    self % sizeN = 0
    self % corner = ZERO
    self % a_bar  = ZERO
    self % outLocalID = 0

  end subroutine kill

  !!
  !! Generate ijk from localID and shape
  !!
  !! Args:
  !!   localID [in] -> Local id of the cell between 1 and product(sizeN)
  !!   sizeN [in]   -> Number of cells in each cardinal direction x,y&z
  !!
  !! Result:
  !!   Array ijk which has integer position in each cardinal direction
  !!
  pure function get_ijk(localID, sizeN) result(ijk)
    integer(shortInt), intent(in)               :: localID
    integer(shortInt), dimension(3), intent(in) :: sizeN
    integer(shortInt), dimension(3)             :: ijk
    integer(shortInt)                           :: temp, base

    temp = localID - 1

    base = temp / sizeN(1)
    ijk(1) = temp - sizeN(1) * base + 1

    temp = base
    base = temp / sizeN(2)
    ijk(2) = temp - sizeN(2) * base + 1

    ijk(3) = base + 1

  end function get_ijk

end module cartesianLattice_class