# Define compilation variables 

all: 
	make -C ./SharedModules
	make -C ./RandomNumbers
	make -C ./ParticleObjects
	make -C ./NuclearData
clean: 
	rm ./objFiles/*.o
	rm ./modFiles/*.mod
	rm ./bin/*.out